# Generated by Django 4.0.5 on 2022-06-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_alter_payable_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payable',
            name='service_type',
            field=models.CharField(choices=[('FAS', 'Gas Service'), ('ELE', 'Electric Energy Service'), ('COM', 'TV/Phone/Internet'), ('TLL', 'Toll Service')], max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card_number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=16),
        ),
    ]
