# Generated by Django 4.0.5 on 2022-06-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_alter_payable_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='card_number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=16, null=True),
        ),
    ]
